### ISSUE TITLE
Default Inbox

### ISSUE THREAD

**Issue by kerim** [mbrock/telegroam#10]
Feature request: Right now notes get sent to the top level of the current Daily Notes Page (DNP). I would prefer them to be grouped under a header "Inbox" - either creating that section if it doesn't exist, or if it does then adding them at the bottom of that section.

**Comment by hugows** [comment]
This is how it works today, right?

**Comment by kerim** [comment]
Sorry, I switched to Logseq after writing this, so I don't know.
