### ISSUE TITLE
Error: Trusted Media Proxy missing

### ISSUE THREAD

**Issue by jagr21** [mbrock/telegroam#12]
Any idea what I'm doing wrong?  I'm getting the following error after I run the Javascript code-block: 
![Captura](https://user-images.githubusercontent.com/67085080/117761888-2376ee00-b1f6-11eb-9532-b829763b4634.PNG)

**Comment by stalal** [comment]
I'm getting the same error. Tinkered around a bit but no success.

**Comment by hugows** [comment]
Hey, did you setup the page like this?

![image](https://user-images.githubusercontent.com/11545/131248781-fb8d98bb-cf70-4441-85b0-83dc08dd7a2e.png)

Working for me.

**Comment by jagr21** [comment]
Working fine now.
