### ISSUE TITLE
Photo/File upload seems to be broken

### ISSUE THREAD

**Issue by 8bitgentleman** [mbrock/telegroam#16]
Has something to do with the proxy I believe. It's returning a 404 for the image and file even though the file can be accessed from the direct telegram link. Also seeing some Cross-Origin Read Blocking (CORB) warnings

**Comment by hugows** [comment]
Working for me. Installed yesterday.

**Comment by 8bitgentleman** [comment]
Interesting, turns out if I use the default proxy and not my own the error goes away
