### ISSUE TITLE
Did this stop working?

### ISSUE THREAD

**Issue by ashishbhateja** [mbrock/telegroam#29]
I was using it fine till yesterday. And now the messages have stopped appearing in Roam. Any ideas?

**Comment by panterarocks49** [comment]
Yes, this stopped working because heroku dropped free plans, I forked the project and deployed my own servers but you will have to reinstall from this link https://github.com/panterarocks49/telegroam (The code and the trusted media proxy attribute changed)

**Comment by ashishbhateja** [comment]
Thank you so much!!
